### PR TITLE
Dev -> Master

### PR DESCRIPTION
**Pull request by ajayns**
@apollonian11 I've added redux-thunk and an example. I'll be updating the docs as well soon.

What I seem to be noticing is that the Webpack hot-reloading doesn't seem to be working fine. Do you notice this issue as well? Do we need to add any configs, are we missing out on anything?

### CODE REVIEW

**Comment by apollonian** [comment]
Um, yeah, we'll have to make a `devServer` key in the config with a `historyApiFallback` set as true.

You can check this file out: https://github.com/shaktigoap/organizer-dashboard/blob/prototype/webpack.config.js

**Comment by ajayns** [comment]
That solves the routing issue, but unsure that helps with reloading. Like if you make a change in a component, it should hot-reload and reflect the changes, but sometimes it doesn't seem to be doing that. @apollonian11

**Comment by apollonian** [comment]
Okay. Will check it out.

**Comment by ajayns** [comment]
Looks like code-splitting with react-loadable is the cause for hot-reloading not working as expected. Is there a workaround for this you know? Or maybe I should remove react-loadable since it's not actually required on a starter. @apollonian11 Opinions?

**Comment by apollonian** [comment]
Any leads on why you think react-loadable is causing the issue? I think it is a webpack 4 issue. https://github.com/jantimon/html-webpack-plugin/issues/895

**Comment by ajayns** [comment]
I'm merging this and opening a new PR for dotenv config @apollonian11

**Pull request merged**
